const dummyData = [
    {
      messageFormat: 'MT',
      messageRef: 'REF123',
      rfcRef: 'RFC456',
      startDate: '2023-10-01',
      endDate: '2023-10-31',
      messageType: 'MT541',
      messageDirection: 'Outgoing',
      senderBIC: 'BIC789',
      receiverBIC: 'BIC987',
      status: 'Completed',
    },
    {
      messageFormat: 'MX',
      messageRef: 'REF124',
      rfcRef: 'RFC457',
      startDate: '2023-09-01',
      endDate: '2023-09-30',
      messageType: 'MX009',
      messageDirection: 'Incoming',
      senderBIC: 'BIC790',
      receiverBIC: 'BIC986',
      status: 'Pending',
    },
    {
      messageFormat: 'MT',
      messageRef: 'REF125',
      rfcRef: 'RFC458',
      startDate: '2023-08-01',
      endDate: '2023-08-31',
      messageType: 'MT103',
      messageDirection: 'Outgoing',
      senderBIC: 'BIC791',
      receiverBIC: 'BIC985',
      status: 'Rejected',
    },
    {
      messageFormat: 'MT',
      messageRef: 'REF126',
      rfcRef: 'RFC459',
      startDate: '2023-10-15',
      endDate: '2023-11-15',
      messageType: 'MT540',
      messageDirection: 'Incoming',
      senderBIC: 'DEUTDEFF',
      receiverBIC: 'CHASUS33',
      status: 'Completed',
    },
    {
      messageFormat: 'MX',
      messageRef: 'REF127',
      rfcRef: 'RFC460',
      startDate: '2023-10-10',
      endDate: '2023-11-10',
      messageType: 'MX502',
      messageDirection: 'Outgoing',
      senderBIC: 'BARCGB22',
      receiverBIC: 'BNPAFRPP',
      status: 'Pending',
    },
    {
      messageFormat: 'MT',
      messageRef: 'REF128',
      rfcRef: 'RFC461',
      startDate: '2023-09-15',
      endDate: '2023-10-15',
      messageType: 'MT542',
      messageDirection: 'Outgoing',
      senderBIC: 'UBSWCHZH',
      receiverBIC: 'CITIUS33',
      status: 'Completed',
    },
    {
      messageFormat: 'MT',
      messageRef: 'REF129',
      rfcRef: 'RFC462',
      startDate: '2023-09-20',
      endDate: '2023-10-20',
      messageType: 'MT543',
      messageDirection: 'Incoming',
      senderBIC: 'RBOSGB2L',
      receiverBIC: 'DEUTDEFF',
      status: 'Processing',
    },
    {
      messageFormat: 'MX',
      messageRef: 'REF130',
      rfcRef: 'RFC463',
      startDate: '2023-10-05',
      endDate: '2023-11-05',
      messageType: 'MX015',
      messageDirection: 'Outgoing',
      senderBIC: 'CRESCHZZ',
      receiverBIC: 'HSBCGB2L',
      status: 'Rejected',
    },
    {
      messageFormat: 'MT',
      messageRef: 'REF131',
      rfcRef: 'RFC464',
      startDate: '2023-08-15',
      endDate: '2023-09-15',
      messageType: 'MT544',
      messageDirection: 'Incoming',
      senderBIC: 'NTRGIT33',
      receiverBIC: 'SOGEFRPP',
      status: 'Completed',
    },
    {
      messageFormat: 'MX',
      messageRef: 'REF132',
      rfcRef: 'RFC465',
      startDate: '2023-09-25',
      endDate: '2023-10-25',
      messageType: 'MX303',
      messageDirection: 'Outgoing',
      senderBIC: 'MIDLGB22',
      receiverBIC: 'DABADKKK',
      status: 'Pending',
    },
    {
      messageFormat: 'MT',
      messageRef: 'REF133',
      rfcRef: 'RFC466',
      startDate: '2023-10-20',
      endDate: '2023-11-20',
      messageType: 'MT545',
      messageDirection: 'Incoming',
      senderBIC: 'BOFAUS3N',
      receiverBIC: 'RBOSIE2D',
      status: 'Processing',
    },
    {
      messageFormat: 'MT',
      messageRef: 'REF134',
      rfcRef: 'RFC467',
      startDate: '2023-08-25',
      endDate: '2023-09-25',
      messageType: 'MT546',
      messageDirection: 'Outgoing',
      senderBIC: 'ABNANL2A',
      receiverBIC: 'HANDFIHH',
      status: 'Completed',
    },
    {
      messageFormat: 'MX',
      messageRef: 'REF135',
      rfcRef: 'RFC468',
      startDate: '2023-09-10',
      endDate: '2023-10-10',
      messageType: 'MX601',
      messageDirection: 'Incoming',
      senderBIC: 'BBVESMM2',
      receiverBIC: 'UNCRIT2B',
      status: 'Rejected',
    }
];

export default dummyData;